from werkzeug.security import generate_password_hash
from app import create_app
from app.ext.database import db
from app.models.user import User
from app.models.question import Question, AnswerChoice

QUESTIONS = [
    {
        "statement": "Qual é o resultado de 2³ + √16?",
        "option_a": "10",
        "option_b": "12",
        "option_c": "14",
        "option_d": "16",
        "option_e": "20",
        "correct_answer": AnswerChoice.B,
        "subject": "Matemática",
        "source": "ENEM",
        "year": 2022,
    },
    {
        "statement": "Um objeto em queda livre, partindo do repouso, percorre qual distância após 2 segundos? (g = 10 m/s²)",
        "option_a": "5 m",
        "option_b": "10 m",
        "option_c": "20 m",
        "option_d": "40 m",
        "option_e": "80 m",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "FUVEST",
        "year": 2021,
    },
    {
        "statement": "Qual é a fórmula molecular da glicose?",
        "option_a": "C₆H₁₂O₅",
        "option_b": "C₆H₁₂O₆",
        "option_c": "C₁₂H₂₂O₁₁",
        "option_d": "C₂H₅OH",
        "option_e": "CH₄O",
        "correct_answer": AnswerChoice.B,
        "subject": "Química",
        "source": "ENEM",
        "year": 2020,
    },
    {
        "statement": "A Independência do Brasil foi proclamada em:",
        "option_a": "7 de setembro de 1889",
        "option_b": "15 de novembro de 1889",
        "option_c": "7 de setembro de 1822",
        "option_d": "22 de abril de 1500",
        "option_e": "13 de maio de 1888",
        "correct_answer": AnswerChoice.C,
        "subject": "História",
        "source": "UNICAMP",
        "year": 2023,
    },
    {
        "statement": "Qual processo celular é responsável pela produção de ATP na presença de oxigênio?",
        "option_a": "Fotossíntese",
        "option_b": "Fermentação",
        "option_c": "Glicólise anaeróbica",
        "option_d": "Respiração celular aeróbica",
        "option_e": "Osmose",
        "correct_answer": AnswerChoice.D,
        "subject": "Biologia",
        "source": "ENEM",
        "year": 2022,
    },
    {
        "statement": "Qual figura de linguagem está presente em 'A vida é uma viagem'?",
        "option_a": "Metonímia",
        "option_b": "Hipérbole",
        "option_c": "Metáfora",
        "option_d": "Ironia",
        "option_e": "Antítese",
        "correct_answer": AnswerChoice.C,
        "subject": "Português",
        "source": "FUVEST",
        "year": 2021,
    },
    {
        "statement": "Qual é o valor de sen(30°)?",
        "option_a": "√3/2",
        "option_b": "√2/2",
        "option_c": "1",
        "option_d": "1/2",
        "option_e": "0",
        "correct_answer": AnswerChoice.D,
        "subject": "Matemática",
        "source": "ENEM",
        "year": 2019,
    },
    {
        "statement": "Qual é o principal gás responsável pelo efeito estufa antropogênico?",
        "option_a": "Oxigênio (O₂)",
        "option_b": "Nitrogênio (N₂)",
        "option_c": "Dióxido de carbono (CO₂)",
        "option_d": "Argônio (Ar)",
        "option_e": "Hidrogênio (H₂)",
        "correct_answer": AnswerChoice.C,
        "subject": "Geografia",
        "source": "ENEM",
        "year": 2023,
    },
    {
        "statement": "A Lei Áurea, que aboliu a escravidão no Brasil, foi assinada em:",
        "option_a": "13 de maio de 1888",
        "option_b": "15 de novembro de 1889",
        "option_c": "7 de setembro de 1822",
        "option_d": "1 de janeiro de 1863",
        "option_e": "28 de setembro de 1871",
        "correct_answer": AnswerChoice.A,
        "subject": "História",
        "source": "UNICAMP",
        "year": 2022,
    },
    {
        "statement": "Um condutor tem resistência de 10 Ω e é submetido a uma tensão de 220 V. Qual é a corrente elétrica que o percorre?",
        "option_a": "2 A",
        "option_b": "10 A",
        "option_c": "22 A",
        "option_d": "220 A",
        "option_e": "2200 A",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "FUVEST",
        "year": 2020,
    },
    {
        "statement": "Um casal deseja ter dois filhos. Qual é a probabilidade de que ambos sejam do sexo masculino?",
        "option_a": "1/2",
        "option_b": "1/4",
        "option_c": "1/8",
        "option_d": "3/4",
        "option_e": "1/3",
        "correct_answer": AnswerChoice.B,
        "subject": "Matemática",
        "source": "ENEM",
        "year": 2021
    },
    {
        "statement": "Qual é a principal função dos ribossomos nas células eucariontes?",
        "option_a": "Respiração celular",
        "option_b": "Armazenamento de genética",
        "option_c": "Síntese de proteínas",
        "option_d": "Digestão intracelular",
        "option_e": "Transporte de lipídios",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "FUVEST",
        "year": 2020
    },
    {
        "statement": "Um corpo de massa 2 kg é submetido a uma força constante de 10 N. Qual a aceleração adquirida pelo corpo?",
        "option_a": "2 m/s²",
        "option_b": "5 m/s²",
        "option_c": "10 m/s²",
        "option_d": "20 m/s²",
        "option_e": "25 m/s²",
        "correct_answer": AnswerChoice.B,
        "subject": "Física",
        "source": "UNESP",
        "year": 2022
    },
    {
        "statement": "O que caracteriza uma ligação química covalente?",
        "option_a": "Transferência definitiva de elétrons",
        "option_b": "Compartilhamento de pares de elétrons",
        "option_c": "Atração entre íons de cargas opostas",
        "option_d": "Formação de uma nuvem eletrônica metálica",
        "option_e": "Interação exclusiva entre gases nobres",
        "correct_answer": AnswerChoice.B,
        "subject": "Química",
        "source": "ENEM",
        "year": 2019
    },
    {
        "statement": "O Primeiro Reinado no Brasil (1822-1831) teve como característica marcante:",
        "option_a": "A abolição imediata da escravidão",
        "option_b": "O fortalecimento do parlamentarismo",
        "option_c": "A outorga da Constituição de 1824 e o Poder Moderador",
        "option_d": "A descentralização administrativa total das províncias",
        "option_e": "A aliança incondicional com a Argentina",
        "correct_answer": AnswerChoice.C,
        "subject": "História",
        "source": "FUVEST",
        "year": 2021
    },
    {
        "statement": "Qual elemento químico possui o símbolo 'K' na tabela periódica?",
        "option_a": "Criptônio",
        "option_b": "Cálcio",
        "option_c": "Potássio",
        "option_d": "Fósforo",
        "option_e": "Cobalto",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "Vunesp",
        "year": 2020
    },
    {
        "statement": "Em um triângulo retângulo, se os catetos medem 3 cm e 4 cm, qual é a medida da hipotenusa?",
        "option_a": "5 cm",
        "option_b": "6 cm",
        "option_c": "7 cm",
        "option_d": "12 cm",
        "option_e": "25 cm",
        "correct_answer": AnswerChoice.A,
        "subject": "Matemática",
        "source": "OBMEP",
        "year": 2018
    },
    {
        "statement": "Qual fenômeno ótico explica a formação do arco-íris?",
        "option_a": "Difração",
        "option_b": "Reflexão total interna apenas",
        "option_c": "Dispersão da luz branca",
        "option_d": "Polarização",
        "option_e": "Interferência destrutiva",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "ENEM",
        "year": 2017
    },
    {
        "statement": "O processo de urbanização brasileiro intensificou-se a partir da década de 1950 devido a:",
        "option_a": "Expansão da fronteira agrícola no Nordeste",
        "option_b": "Industrialização e o êxodo rural",
        "option_c": "Descentralização política das capitais",
        "option_d": "Fim do ciclo do café em Minas Gerais",
        "option_e": "Redução da taxa de natalidade urbana",
        "correct_answer": AnswerChoice.B,
        "subject": "Geografia",
        "source": "UNICAMP",
        "year": 2022
    },
    {
        "statement": "Qual organela é responsável pela fotossíntese nas plantas?",
        "option_a": "Mitocôndria",
        "option_b": "Complexo de Golgi",
        "option_c": "Cloroplasto",
        "option_d": "Lisossomo",
        "option_e": "Vacúolo",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "ENEM",
        "year": 2023
    },
    {
        "statement": "Uma das principais causas da Revolução Francesa de 1789 foi:",
        "option_a": "A unificação da Alemanha sob o governo de Napoleão.",
        "option_b": "A crise financeira do Estado e a injustiça do sistema tributário.",
        "option_c": "A ascensão do socialismo científico no seio da burguesia.",
        "option_d": "O apoio do Rei Luís XVI às ideias iluministas radicais.",
        "option_e": "A aliança militar entre a França e a Inglaterra contra a Áustria.",
        "correct_answer": AnswerChoice.B,
        "subject": "História",
        "source": "FUVEST",
        "year": 2019
    },
    {
        "statement": "Um carro percorre uma distância de 150 km em 2 horas. Qual é a sua velocidade média em km/h?",
        "option_a": "60",
        "option_b": "70",
        "option_c": "75",
        "option_d": "80",
        "option_e": "90",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "ENEM",
        "year": 2015
    },
    {
        "statement": "O principal gás responsável pelo efeito estufa, cuja concentração tem aumentado devido à queima de combustíveis fósseis, é o:",
        "option_a": "Oxigênio (O₂)",
        "option_b": "Nitrogênio (N₂)",
        "option_c": "Dióxido de carbono (CO₂)",
        "option_d": "Argônio (Ar)",
        "option_e": "Hélio (He)",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "UNESP",
        "year": 2021
    },
    {
        "statement": "Qual é o valor de x na equação 2x + 5 = 15?",
        "option_a": "2",
        "option_b": "5",
        "option_c": "10",
        "option_d": "15",
        "option_e": "20",
        "correct_answer": AnswerChoice.B,
        "subject": "Matemática",
        "source": "FATEC",
        "year": 2018
    },
    {
        "statement": "A produção de ATP na respiração celular ocorre majoritariamente em qual organela?",
        "option_a": "Núcleo",
        "option_b": "Retículo endoplasmático",
        "option_c": "Mitocôndria",
        "option_d": "Peroxissomo",
        "option_e": "Ribossomo",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "UNICAMP",
        "year": 2022
    },
    {
        "statement": "No Brasil, a bacia hidrográfica com o maior potencial hidrelétrico instalado é a do:",
        "option_a": "Amazonas",
        "option_b": "Paraná",
        "option_c": "São Francisco",
        "option_d": "Uruguai",
        "option_e": "Parnaíba",
        "correct_answer": AnswerChoice.B,
        "subject": "Geografia",
        "source": "FUVEST",
        "year": 2020
    },
    {
        "statement": "O pH de uma solução neutra a 25°C é:",
        "option_a": "0",
        "option_b": "1",
        "option_c": "7",
        "option_d": "10",
        "option_e": "14",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "UERJ",
        "year": 2019
    },
    {
        "statement": "Qual autor brasileiro escreveu a obra 'Dom Casmurro'?",
        "option_a": "Machado de Assis",
        "option_b": "José de Alencar",
        "option_c": "Clarice Lispector",
        "option_d": "Graciliano Ramos",
        "option_e": "Jorge Amado",
        "correct_answer": AnswerChoice.A,
        "subject": "Literatura",
        "source": "ENEM",
        "year": 2017
    },
    {
        "statement": "A primeira lei de Newton, também conhecida como Princípio da Inércia, afirma que:",
        "option_a": "A força é igual à massa vezes a aceleração.",
        "option_b": "Para toda ação existe uma reação oposta e de igual intensidade.",
        "option_c": "Um corpo em repouso tende a permanecer em repouso se a resultante das forças for nula.",
        "option_d": "A energia não pode ser criada nem destruída, apenas transformada.",
        "option_e": "A velocidade da luz é constante no vácuo.",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "ITA",
        "year": 2021
    },
    {
        "statement": "Em uma PG (Progressão Geométrica) de razão 2, se o primeiro termo é 3, qual é o quarto termo?",
        "option_a": "9",
        "option_b": "12",
        "option_c": "24",
        "option_d": "48",
        "option_e": "18",
        "correct_answer": AnswerChoice.C,
        "subject": "Matemática",
        "source": "Vunesp",
        "year": 2023
    },
    {
        "statement": "Qual é a unidade de medida da resistência elétrica no Sistema Internacional?",
        "option_a": "Volt",
        "option_b": "Ampere",
        "option_c": "Ohm",
        "option_d": "Watt",
        "option_e": "Joule",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "UNESP",
        "year": 2021
    },
    {
        "statement": "O processo de divisão celular que resulta em quatro células-filhas com metade do número de cromossomos da célula-mãe é a:",
        "option_a": "Mitose",
        "option_b": "Meiose",
        "option_c": "Fissão binária",
        "option_d": "Gemulação",
        "option_e": "Espitulação",
        "correct_answer": AnswerChoice.B,
        "subject": "Biologia",
        "source": "ENEM",
        "year": 2020
    },
    {
        "statement": "O volume de um cilindro com raio da base 2m e altura 5m é (considere π = 3):",
        "option_a": "20 m³",
        "option_b": "30 m³",
        "option_c": "40 m³",
        "option_d": "60 m³",
        "option_e": "100 m³",
        "correct_answer": AnswerChoice.D,
        "subject": "Matemática",
        "source": "Vunesp",
        "year": 2019
    },
    {
        "statement": "A principal característica do Iluminismo foi a valorização da:",
        "option_a": "Tradição religiosa",
        "option_b": "Razão e ciência",
        "option_c": "Monarquia absoluta",
        "option_d": "Estrutura feudal",
        "option_e": "Escravidão",
        "correct_answer": AnswerChoice.B,
        "subject": "História",
        "source": "UNICAMP",
        "year": 2022
    },
    {
        "statement": "Qual camada da atmosfera é responsável por filtrar a radiação ultravioleta do Sol?",
        "option_a": "Troposfera",
        "option_b": "Mesosfera",
        "option_c": "Camada de Ozônio",
        "option_d": "Exosfera",
        "option_e": "Termosfera",
        "correct_answer": AnswerChoice.C,
        "subject": "Geografia",
        "source": "ENEM",
        "year": 2018
    },
    {
        "statement": "A fórmula molecular do benzeno é:",
        "option_a": "C6H12",
        "option_b": "C6H6",
        "option_c": "CH4",
        "option_d": "C2H5OH",
        "option_e": "C3H8",
        "correct_answer": AnswerChoice.B,
        "subject": "Química",
        "source": "FUVEST",
        "year": 2020
    },
    {
        "statement": "Quem é o autor do poema 'I-Juca-Pirama'?",
        "option_a": "Gonçalves Dias",
        "option_b": "Castro Alves",
        "option_c": "Álvares de Azevedo",
        "option_d": "Casimiro de Abreu",
        "option_e": "Manuel Bandeira",
        "correct_answer": AnswerChoice.A,
        "subject": "Literatura",
        "source": "FUVEST",
        "year": 2017
    },
    {
        "statement": "A aceleração da gravidade na superfície da Terra é aproximadamente:",
        "option_a": "1 m/s²",
        "option_b": "5 m/s²",
        "option_c": "9,8 m/s²",
        "option_d": "15 m/s²",
        "option_e": "20 m/s²",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "ENEM",
        "year": 2019
    },
    {
        "statement": "Qual dos seguintes elementos é um metal alcalino?",
        "option_a": "Magnésio",
        "option_b": "Sódio",
        "option_c": "Cálcio",
        "option_d": "Ferro",
        "option_e": "Alumínio",
        "correct_answer": AnswerChoice.B,
        "subject": "Química",
        "source": "UNESP",
        "year": 2022
    },
    {
        "statement": "A função f(x) = x² - 4x + 3 possui raízes em:",
        "option_a": "1 e 3",
        "option_b": "2 e 4",
        "option_c": "-1 e -3",
        "option_d": "0 e 3",
        "option_e": "1 e -3",
        "correct_answer": AnswerChoice.A,
        "subject": "Matemática",
        "source": "ENEM",
        "year": 2021
    },
    {
        "statement": "O período conhecido como Guerra Fria foi marcado pela disputa entre:",
        "option_a": "Brasil e Argentina",
        "option_b": "EUA e URSS",
        "option_c": "Alemanha e França",
        "option_d": "China e Japão",
        "option_e": "Inglaterra e Portugal",
        "correct_answer": AnswerChoice.B,
        "subject": "História",
        "source": "FUVEST",
        "year": 2018
    },
    {
        "statement": "A respiração traqueal é característica de qual grupo de animais?",
        "option_a": "Peixes",
        "option_b": "Mamíferos",
        "option_c": "Insetos",
        "option_d": "Anfíbios",
        "option_e": "Aves",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "UNESP",
        "year": 2021
    },
    {
        "statement": "No movimento uniforme (MU), a velocidade é:",
        "option_a": "Variável",
        "option_b": "Sempre nula",
        "option_c": "Constante",
        "option_d": "Igual à aceleração",
        "option_e": "Inversamente proporcional ao tempo",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "ENEM",
        "year": 2016
    },
    {
        "statement": "O tratado que dividiu as terras da América entre Portugal e Espanha foi o de:",
        "option_a": "Madri",
        "option_b": "Utrecht",
        "option_c": "Tordesilhas",
        "option_d": "Badajoz",
        "option_e": "Petrópolis",
        "correct_answer": AnswerChoice.C,
        "subject": "História",
        "source": "FATEC",
        "year": 2019
    },
    {
        "statement": "Qual destas substâncias é um ácido forte?",
        "option_a": "H2O",
        "option_b": "NH3",
        "option_c": "HCl",
        "option_d": "CH3COOH",
        "option_e": "NaOH",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "FUVEST",
        "year": 2022
    },
    {
        "statement": "O conjunto dos números naturais é representado por:",
        "option_a": "Z",
        "option_b": "Q",
        "option_c": "N",
        "option_d": "R",
        "option_e": "C",
        "correct_answer": AnswerChoice.C,
        "subject": "Matemática",
        "source": "Vunesp",
        "year": 2020
    },
    {
        "statement": "A principal fonte de energia para a vida na Terra é:",
        "option_a": "O calor da Terra",
        "option_b": "A energia nuclear",
        "option_c": "O Sol",
        "option_d": "O petróleo",
        "option_e": "O vento",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "ENEM",
        "year": 2017
    },
    {
        "statement": "Qual o nome da primeira capital do Brasil?",
        "option_a": "Rio de Janeiro",
        "option_b": "São Paulo",
        "option_c": "Salvador",
        "option_d": "Brasília",
        "option_e": "Olinda",
        "correct_answer": AnswerChoice.C,
        "subject": "História",
        "source": "MACKENZIE",
        "year": 2018
    },
    {
        "statement": "A força de atração entre duas massas é descrita pela Lei da:",
        "option_a": "Termodinâmica",
        "option_b": "Relatividade",
        "option_c": "Gravitação Universal",
        "option_d": "Eletrostática",
        "option_e": "Refração",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "FUVEST",
        "year": 2021
    },
    {
        "statement": "Uma solução com pH igual a 10 é considerada:",
        "option_a": "Ácida",
        "option_b": "Neutra",
        "option_c": "Básica",
        "option_d": "Anfótera",
        "option_e": "Insolúvel",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "ENEM",
        "year": 2023
    },
    {
        "statement": "Qual o nome do processo de transformação do gelo em vapor d'água diretamente?",
        "option_a": "Fusão",
        "option_b": "Solidificação",
        "option_c": "Sublimação",
        "option_d": "Condensação",
        "option_e": "Vaporização",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "Vunesp",
        "year": 2021
    },
    {
        "statement": "A área de um círculo de raio 3 cm é (considere π = 3,14):",
        "option_a": "9,42 cm²",
        "option_b": "18,84 cm²",
        "option_c": "28,26 cm²",
        "option_d": "31,4 cm²",
        "option_e": "40,0 cm²",
        "correct_answer": AnswerChoice.C,
        "subject": "Matemática",
        "source": "ENEM",
        "year": 2020
    },
    {
        "statement": "Quem foi o principal líder da Independência da Índia contra o domínio britânico?",
        "option_a": "Nelson Mandela",
        "option_b": "Mahatma Gandhi",
        "option_c": "Simon Bolívar",
        "option_d": "Winston Churchill",
        "option_e": "Mao Tsé-Tung",
        "correct_answer": AnswerChoice.B,
        "subject": "História",
        "source": "UNICAMP",
        "year": 2019
    },
    {
        "statement": "O fenômeno da reflexão da luz em uma superfície plana segue a regra de que o ângulo de incidência é:",
        "option_a": "Metade do ângulo de reflexão",
        "option_b": "O dobro do ângulo de reflexão",
        "option_c": "Igual ao ângulo de reflexão",
        "option_d": "Independente do ângulo de reflexão",
        "option_e": "Sempre 90 graus",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "ENEM",
        "year": 2018
    },
    {
        "statement": "Qual tipo de rocha é formado pelo resfriamento do magma?",
        "option_a": "Sedimentar",
        "option_b": "Metamórfica",
        "option_c": "Ígnea",
        "option_d": "Calcária",
        "option_e": "Arenosa",
        "correct_answer": AnswerChoice.C,
        "subject": "Geografia",
        "source": "FUVEST",
        "year": 2022
    },
    {
        "statement": "A membrana plasmática é composta principalmente por:",
        "option_a": "Apenas proteínas",
        "option_b": "Apenas carboidratos",
        "option_c": "Fosfolipídios e proteínas",
        "option_d": "Ácidos nucleicos",
        "option_e": "Sais minerais",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "UNICAMP",
        "year": 2023
    },
    {
        "statement": "O valor de log10(100) é:",
        "option_a": "1",
        "option_b": "2",
        "option_c": "10",
        "option_d": "50",
        "option_e": "100",
        "correct_answer": AnswerChoice.B,
        "subject": "Matemática",
        "source": "ENEM",
        "year": 2019
    },
    {
        "statement": "A abolição da escravidão no Brasil ocorreu em 1888 através da:",
        "option_a": "Lei Eusébio de Queirós",
        "option_b": "Lei do Ventre Livre",
        "option_c": "Lei Áurea",
        "option_d": "Lei dos Sexagenários",
        "option_e": "Constituição de 1891",
        "correct_answer": AnswerChoice.C,
        "subject": "História",
        "source": "ENEM",
        "year": 2016
    },
    {
        "statement": "Qual o elemento químico mais abundante no universo?",
        "option_a": "Oxigênio",
        "option_b": "Carbono",
        "option_c": "Hidrogênio",
        "option_d": "Hélio",
        "option_e": "Nitrogênio",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "ITA",
        "year": 2020
    },
    {
        "statement": "O bioma brasileiro caracterizado por árvores de troncos tortuosos e casca grossa é o:",
        "option_a": "Pantanal",
        "option_b": "Pampa",
        "option_c": "Cerrado",
        "option_d": "Amazônia",
        "option_e": "Mata Atlântica",
        "correct_answer": AnswerChoice.C,
        "subject": "Geografia",
        "source": "UNESP",
        "year": 2021
    },
    {
        "statement": "Qual é o principal componente do gás natural?",
        "option_a": "Etano",
        "option_b": "Metano",
        "option_c": "Propano",
        "option_d": "Butano",
        "option_e": "Pentano",
        "correct_answer": AnswerChoice.B,
        "subject": "Química",
        "source": "ENEM",
        "year": 2020
    },
    {
        "statement": "A primeira lei da Termodinâmica trata essencialmente de:",
        "option_a": "Conservação da carga elétrica",
        "option_b": "Conservação da massa",
        "option_c": "Conservação da energia",
        "option_d": "Aumento da entropia",
        "option_e": "Dilatação térmica",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "FUVEST",
        "year": 2021
    },
    {
        "statement": "Qual é o valor de cos(60°)?",
        "option_a": "0",
        "option_b": "1/2",
        "option_c": "√2/2",
        "option_d": "√3/2",
        "option_e": "1",
        "correct_answer": AnswerChoice.B,
        "subject": "Matemática",
        "source": "Vunesp",
        "year": 2022
    },
    {
        "statement": "O DNA é composto por unidades chamadas nucleotídeos. Qual das bases nitrogenadas abaixo NÃO pertence ao DNA?",
        "option_a": "Adenina",
        "option_b": "Guanina",
        "option_c": "Citosina",
        "option_d": "Timina",
        "option_e": "Uracila",
        "correct_answer": AnswerChoice.E,
        "subject": "Biologia",
        "source": "UNICAMP",
        "year": 2023
    },
    {
        "statement": "A 'Noite dos Cristais' (1938) foi um evento marcante para a ascensão do:",
        "option_a": "Socialismo na Rússia",
        "option_b": "Fascismo na Itália",
        "option_c": "Nazismo na Alemanha",
        "option_d": "Franquismo na Espanha",
        "option_e": "Salazarismo em Portugal",
        "correct_answer": AnswerChoice.C,
        "subject": "História",
        "source": "FUVEST",
        "year": 2020
    },
    {
        "statement": "Qual é a principal bacia hidrográfica do Nordeste brasileiro, importante para a geração de energia e irrigação?",
        "option_a": "Bacia do Amazonas",
        "option_b": "Bacia do Paraná",
        "option_c": "Bacia do São Francisco",
        "option_d": "Bacia do Tocantins",
        "option_e": "Bacia do Parnaíba",
        "correct_answer": AnswerChoice.C,
        "subject": "Geografia",
        "source": "ENEM",
        "year": 2019
    },
    {
        "statement": "O que indica o número atômico (Z) de um elemento químico?",
        "option_a": "A soma de prótons e nêutrons",
        "option_b": "A quantidade de elétrons na camada de valência",
        "option_c": "A quantidade de prótons no núcleo",
        "option_d": "A massa total do átomo",
        "option_e": "A quantidade de nêutrons no núcleo",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "ENEM",
        "year": 2021
    },
    {
        "statement": "Um espelho côncavo produz uma imagem real, invertida e do mesmo tamanho que o objeto quando este é colocado:",
        "option_a": "No foco",
        "option_b": "Entre o foco e o vértice",
        "option_c": "No centro de curvatura",
        "option_d": "Além do centro de curvatura",
        "option_e": "No infinito",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "UNESP",
        "year": 2018
    },
    {
        "statement": "Em um mapa com escala 1:100.000, uma distância de 5 cm representa quantos quilômetros no terreno real?",
        "option_a": "0,5 km",
        "option_b": "5 km",
        "option_c": "50 km",
        "option_d": "500 km",
        "option_e": "5.000 km",
        "correct_answer": AnswerChoice.B,
        "subject": "Geografia",
        "source": "FUVEST",
        "year": 2021
    },
    {
        "statement": "A Revolta da Vacina (1904) ocorreu na cidade do Rio de Janeiro e teve como um de seus motivos:",
        "option_a": "A alta dos preços dos alimentos",
        "option_b": "A obrigatoriedade da vacinação contra a varíola",
        "option_c": "A luta pelo voto feminino",
        "option_d": "A expulsão de imigrantes europeus",
        "option_e": "O fechamento do Congresso Nacional",
        "correct_answer": AnswerChoice.B,
        "subject": "História",
        "source": "ENEM",
        "year": 2022
    },
    {
        "statement": "Qual é a derivada da função f(x) = x³?",
        "option_a": "3x",
        "option_b": "x²",
        "option_c": "3x²",
        "option_d": "3x³",
        "option_e": "x/3",
        "correct_answer": AnswerChoice.C,
        "subject": "Matemática",
        "source": "Cálculo I / Escola Naval",
        "year": 2019
    },
    {
        "statement": "As ligações de hidrogênio ocorrem entre o hidrogênio e quais outros elementos?",
        "option_a": "C, H, O",
        "option_b": "F, O, N",
        "option_c": "Li, Na, K",
        "option_d": "Cl, Br, I",
        "option_e": "S, P, C",
        "correct_answer": AnswerChoice.B,
        "subject": "Química",
        "source": "FUVEST",
        "year": 2023
    },
    {
        "statement": "A produção de insulina no corpo humano ocorre em qual órgão?",
        "option_a": "Fígado",
        "option_b": "Estômago",
        "option_c": "Pâncreas",
        "option_d": "Rim",
        "option_e": "Baço",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "UNESP",
        "year": 2022
    },
    {
        "statement": "O fenômeno do El Niño caracteriza-se pelo:",
        "option_a": "Resfriamento das águas do Atlântico Sul",
        "option_b": "Aquecimento das águas do Pacífico Equatorial",
        "option_c": "Congelamento das águas do Ártico",
        "option_d": "Aumento das marés no Índico",
        "option_e": "Secas extremas na região Sul do Brasil",
        "correct_answer": AnswerChoice.B,
        "subject": "Geografia",
        "source": "ENEM",
        "year": 2020
    },
    {
        "statement": "Qual cientista é conhecido pela proposição da Teoria da Relatividade Geral?",
        "option_a": "Isaac Newton",
        "option_b": "Galileu Galilei",
        "option_c": "Albert Einstein",
        "option_d": "Stephen Hawking",
        "option_e": "Marie Curie",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "FATEC",
        "year": 2017
    },
    {
        "statement": "O valor numérico da expressão (10² + 5²) / 5 é:",
        "option_a": "15",
        "option_b": "20",
        "option_c": "25",
        "option_d": "30",
        "option_e": "125",
        "correct_answer": AnswerChoice.C,
        "subject": "Matemática",
        "source": "Vunesp",
        "year": 2021
    },
    {
        "statement": "O movimento artístico que buscou romper com o passado e valorizar a tecnologia, a velocidade e as máquinas foi o:",
        "option_a": "Cubismo",
        "option_b": "Surrealismo",
        "option_c": "Futurismo",
        "option_d": "Dadaísmo",
        "option_e": "Impressionismo",
        "correct_answer": AnswerChoice.C,
        "subject": "Artes/História",
        "source": "ENEM",
        "year": 2018
    },
    {
        "statement": "Qual dos seguintes biomas é exclusivo do território brasileiro?",
        "option_a": "Cerrado",
        "option_b": "Caatinga",
        "option_c": "Pampa",
        "option_d": "Pantanal",
        "option_e": "Mata Atlântica",
        "correct_answer": AnswerChoice.B,
        "subject": "Biologia",
        "source": "FUVEST",
        "year": 2022
    },
    {
        "statement": "A densidade é definida pela relação entre:",
        "option_a": "Peso e volume",
        "option_b": "Massa e área",
        "option_c": "Massa e volume",
        "option_d": "Força e área",
        "option_e": "Pressão e temperatura",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "ENEM",
        "year": 2015
    },
    {
        "statement": "A soma dos ângulos internos de um hexágono regular é:",
        "option_a": "360°",
        "option_b": "540°",
        "option_c": "720°",
        "option_d": "900°",
        "option_e": "1080°",
        "correct_answer": AnswerChoice.C,
        "subject": "Matemática",
        "source": "Vunesp",
        "year": 2020
    },
    {
        "statement": "A Segunda Revolução Industrial foi marcada pelo uso do:",
        "option_a": "Carvão mineral e ferro",
        "option_b": "Petróleo e eletricidade",
        "option_c": "Energia solar e silício",
        "option_d": "Vapor e madeira",
        "option_e": "Trabalho artesanal",
        "correct_answer": AnswerChoice.B,
        "subject": "História",
        "source": "UNICAMP",
        "year": 2021
    },
    {
        "statement": "Qual a principal característica das gimnospermas, como os pinheiros?",
        "option_a": "Presença de frutos",
        "option_b": "Presença de sementes nuas (sem frutos)",
        "option_c": "Dependência de água para a fecundação",
        "option_d": "Ausência de vasos condutores",
        "option_e": "Presença de flores coloridas",
        "correct_answer": AnswerChoice.B,
        "subject": "Biologia",
        "source": "ENEM",
        "year": 2022
    },
    {
        "statement": "A força peso de um objeto na Lua é menor que na Terra porque:",
        "option_a": "A massa do objeto diminui",
        "option_b": "A aceleração da gravidade na Lua é menor",
        "option_c": "Não há atmosfera na Lua",
        "option_d": "A distância ao Sol é maior",
        "option_e": "A Lua não possui núcleo metálico",
        "correct_answer": AnswerChoice.B,
        "subject": "Física",
        "source": "ENEM",
        "year": 2019
    },
    {
        "statement": "O Mercosul é um bloco econômico que tem como membros fundadores:",
        "option_a": "Brasil, Chile, Peru e Colômbia",
        "option_b": "Brasil, Argentina, Uruguai e Paraguai",
        "option_c": "Brasil, México, Argentina e Bolívia",
        "option_d": "Argentina, Uruguai, Chile e Equador",
        "option_e": "Venezuela, Brasil, Guiana e Suriname",
        "correct_answer": AnswerChoice.B,
        "subject": "Geografia",
        "source": "UNICAMP",
        "year": 2020
    },
    {
        "statement": "Qual o produto da reação entre um ácido e uma base?",
        "option_a": "Água e sal",
        "option_b": "Apenas água",
        "option_c": "Apenas sal",
        "option_d": "Gás hidrogênio",
        "option_e": "Óxido metálico",
        "correct_answer": AnswerChoice.A,
        "subject": "Química",
        "source": "UNESP",
        "year": 2021
    },
    {
        "statement": "A Idade Média na Europa foi caracterizada pelo sistema econômico e social conhecido como:",
        "option_a": "Capitalismo",
        "option_b": "Mercantilismo",
        "option_c": "Feudalismo",
        "option_d": "Socialismo",
        "option_e": "Escravismo",
        "correct_answer": AnswerChoice.C,
        "subject": "História",
        "source": "FUVEST",
        "year": 2018
    },
    {
        "statement": "Um capital de R$ 1.000,00 aplicado a juros simples de 10% ao mês resultará em qual montante após 2 meses?",
        "option_a": "R$ 1.100,00",
        "option_b": "R$ 1.200,00",
        "option_c": "R$ 1.210,00",
        "option_d": "R$ 1.300,00",
        "option_e": "R$ 1.500,00",
        "correct_answer": AnswerChoice.B,
        "subject": "Matemática",
        "source": "ENEM",
        "year": 2017
    },
    {
        "statement": "O processo de transformar nitrogênio atmosférico em amônia por bactérias no solo é chamado de:",
        "option_a": "Desnitrificação",
        "option_b": "Fixação biológica",
        "option_c": "Lixiviação",
        "option_d": "Transpiração",
        "option_e": "Eutrofização",
        "correct_answer": AnswerChoice.B,
        "subject": "Biologia",
        "source": "UNICAMP",
        "year": 2022
    },
    {
        "statement": "A grandeza física 'Trabalho' é medida em qual unidade no SI?",
        "option_a": "Newton",
        "option_b": "Pascal",
        "option_c": "Joule",
        "option_d": "Watt",
        "option_e": "Tesla",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "FATEC",
        "year": 2020
    },
    {
        "statement": "Qual país foi o berço da Revolução Industrial?",
        "option_a": "França",
        "option_b": "EUA",
        "option_c": "Inglaterra",
        "option_d": "Alemanha",
        "option_e": "Japão",
        "correct_answer": AnswerChoice.C,
        "subject": "História",
        "source": "ENEM",
        "year": 2016
    },
    {
        "statement": "O fenômeno de dispersão da luz branca ao passar por um prisma gera:",
        "option_a": "Apenas luz ultravioleta",
        "option_b": "O espectro visível (cores do arco-íris)",
        "option_c": "Luz laser",
        "option_d": "Sombra total",
        "option_e": "Radiação gama",
        "correct_answer": AnswerChoice.B,
        "subject": "Física",
        "source": "FUVEST",
        "year": 2022
    },
    {
        "statement": "A célula nervosa responsável pela condução dos impulsos elétricos é o:",
        "option_a": "Miócito",
        "option_b": "Osteócito",
        "option_c": "Neurônio",
        "option_d": "Leucócito",
        "option_e": "Adipócito",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "UNESP",
        "year": 2023
    },
    {
        "statement": "A fórmula química do sal de cozinha comum é:",
        "option_a": "KCl",
        "option_b": "MgCl2",
        "option_c": "NaCl",
        "option_d": "CaCl2",
        "option_e": "LiCl",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "Vunesp",
        "year": 2019
    },
    {
        "statement": "O deserto do Saara está localizado em qual continente?",
        "option_a": "Ásia",
        "option_b": "América",
        "option_c": "África",
        "option_d": "Oceania",
        "option_e": "Europa",
        "correct_answer": AnswerChoice.C,
        "subject": "Geografia",
        "source": "OBMEP",
        "year": 2020
    },
    {
        "statement": "Qual o valor da raiz quadrada de 144?",
        "option_a": "10",
        "option_b": "11",
        "option_c": "12",
        "option_d": "13",
        "option_e": "14",
        "correct_answer": AnswerChoice.C,
        "subject": "Matemática",
        "source": "Vunesp",
        "year": 2018
    },
    {
        "statement": "A Era Vargas (1930-1945) terminou com a queda de Getúlio Vargas e a implantação de um regime:",
        "option_a": "Monárquico",
        "option_b": "Socialista",
        "option_c": "Democrático-Liberal",
        "option_d": "Teocrático",
        "option_e": "Ditatorial Militar (imediato)",
        "correct_answer": AnswerChoice.C,
        "subject": "História",
        "source": "FUVEST",
        "year": 2021
    },
    {
        "statement": "Qual desses planetas é conhecido como o 'Planeta Vermelho'?",
        "option_a": "Mercúrio",
        "option_b": "Vênus",
        "option_c": "Marte",
        "option_d": "Júpiter",
        "option_e": "Saturno",
        "correct_answer": AnswerChoice.C,
        "subject": "Física/Astronomia",
        "source": "ENEM",
        "year": 2023
    },
    {
        "statement": "A membrana que envolve o pulmão humano chama-se:",
        "option_a": "Pericárdio",
        "option_b": "Peritônio",
        "option_c": "Pleura",
        "option_d": "Meninge",
        "option_e": "Bainha de mielina",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "UNESP",
        "year": 2021
    },
    {
        "statement": "Na tabela periódica, as colunas verticais são chamadas de:",
        "option_a": "Períodos",
        "option_b": "Níveis",
        "option_c": "Famílias ou Grupos",
        "option_d": "Séries",
        "option_e": "Camadas",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "ENEM",
        "year": 2022
    },
    {
        "statement": "Quem pintou a 'Monalisa'?",
        "option_a": "Michelangelo",
        "option_b": "Donatello",
        "option_c": "Leonardo da Vinci",
        "option_d": "Rafael Sanzio",
        "option_e": "Vincent van Gogh",
        "correct_answer": AnswerChoice.C,
        "subject": "História/Artes",
        "source": "OBMEP",
        "year": 2017
    },
    {
        "statement": "Qual é a principal função do intestino grosso no sistema digestório?",
        "option_a": "Produção de bile",
        "option_b": "Digestão de proteínas",
        "option_c": "Absorção de água e formação de fezes",
        "option_d": "Absorção de lipídios",
        "option_e": "Secreção de insulina",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "ENEM",
        "year": 2021
    },
    {
        "statement": "O movimento de translação da Terra é responsável por qual fenômeno?",
        "option_a": "Alternância entre dia e noite",
        "option_b": "As estações do ano",
        "option_c": "O magnetismo terrestre",
        "option_d": "A formação de marés",
        "option_e": "A ocorrência de eclipses solares",
        "correct_answer": AnswerChoice.B,
        "subject": "Geografia",
        "source": "FUVEST",
        "year": 2019
    },
    {
        "statement": "Qual o valor de x na proporção 3/x = 9/12?",
        "option_a": "2",
        "option_b": "4",
        "option_c": "6",
        "option_d": "8",
        "option_e": "10",
        "correct_answer": AnswerChoice.B,
        "subject": "Matemática",
        "source": "Vunesp",
        "year": 2022
    },
    {
        "statement": "A força que mantém os planetas em órbita ao redor do Sol é a:",
        "option_a": "Força Nuclear Forte",
        "option_b": "Força Eletromagnética",
        "option_c": "Força Gravitacional",
        "option_d": "Força de Atrito",
        "option_e": "Força Centrípeta apenas",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "ENEM",
        "year": 2020
    },
    {
        "statement": "Qual o principal metal constituinte do aço?",
        "option_a": "Cobre",
        "option_b": "Alumínio",
        "option_c": "Ferro",
        "option_d": "Zinco",
        "option_e": "Chumbo",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "FUVEST",
        "year": 2021
    },
    {
        "statement": "O período conhecido como 'Milagre Econômico' brasileiro ocorreu durante qual regime?",
        "option_a": "Era Vargas",
        "option_b": "República Velha",
        "option_c": "Ditadura Militar",
        "option_d": "Nova República",
        "option_e": "Segundo Reinado",
        "correct_answer": AnswerChoice.C,
        "subject": "História",
        "source": "ENEM",
        "year": 2018
    },
    {
        "statement": "A osmose é um processo de transporte passivo que envolve o movimento de:",
        "option_a": "Solutos do meio hipertônico para o hipotônico",
        "option_b": "Solvente do meio hipotônico para o hipertônico",
        "option_c": "Gases contra o gradiente de concentração",
        "option_d": "Íons através de bombas de sódio e potássio",
        "option_e": "Proteínas por vesículas",
        "correct_answer": AnswerChoice.B,
        "subject": "Biologia",
        "source": "UNICAMP",
        "year": 2022
    },
    {
        "statement": "Qual a principal característica de uma solução ácida?",
        "option_a": "pH maior que 7",
        "option_b": "Concentração de íons H+ maior que OH-",
        "option_c": "Sabor adstringente",
        "option_d": "Não conduzir eletricidade",
        "option_e": "Cor azulada em presença de fenolftaleína",
        "correct_answer": AnswerChoice.B,
        "subject": "Química",
        "source": "UNESP",
        "year": 2023
    },
    {
        "statement": "O autor da obra 'O Cortiço', expoente do Naturalismo no Brasil, é:",
        "option_a": "Machado de Assis",
        "option_b": "Aluísio Azevedo",
        "option_c": "Raul Pompeia",
        "option_d": "Lima Barreto",
        "option_e": "Euclides da Cunha",
        "correct_answer": AnswerChoice.B,
        "subject": "Literatura",
        "source": "FUVEST",
        "year": 2017
    },
    {
        "statement": "Qual é a soma dos ângulos internos de um triângulo?",
        "option_a": "90°",
        "option_b": "180°",
        "option_c": "270°",
        "option_d": "360°",
        "option_e": "540°",
        "correct_answer": AnswerChoice.B,
        "subject": "Matemática",
        "source": "ENEM",
        "year": 2015
    },
    {
        "statement": "A queda do Muro de Berlim em 1989 simbolizou o fim de qual era?",
        "option_a": "Era Napoleônica",
        "option_b": "Guerra Fria",
        "option_c": "Primeira Guerra Mundial",
        "option_d": "Absolutismo",
        "option_e": "Colonialismo Africano",
        "correct_answer": AnswerChoice.B,
        "subject": "História",
        "source": "UNICAMP",
        "year": 2021
    },
    {
        "statement": "O fenômeno de propagação do calor no vácuo ocorre por:",
        "option_a": "Condução",
        "option_b": "Convecção",
        "option_c": "Irradiação",
        "option_d": "Refração",
        "option_e": "Difusão",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "UNESP",
        "year": 2020
    },
    {
        "statement": "Qual organela celular é responsável pela desintoxicação de álcool e drogas no fígado?",
        "option_a": "Ribossomo",
        "option_b": "Retículo Endoplasmático Liso",
        "option_c": "Retículo Endoplasmático Rugoso",
        "option_d": "Complexo de Golgi",
        "option_e": "Lisossomo",
        "correct_answer": AnswerChoice.B,
        "subject": "Biologia",
        "source": "FUVEST",
        "year": 2022
    },
    {
        "statement": "O hidrocarboneto alcano com dois átomos de carbono é o:",
        "option_a": "Metano",
        "option_b": "Etano",
        "option_c": "Eteno",
        "option_d": "Etino",
        "option_e": "Propano",
        "correct_answer": AnswerChoice.B,
        "subject": "Química",
        "source": "Vunesp",
        "year": 2019
    },
    {
        "statement": "Em qual cidade brasileira ocorreu a Inconfidência Mineira?",
        "option_a": "Belo Horizonte",
        "option_b": "Ouro Preto",
        "option_c": "Mariana",
        "option_d": "Congonhas",
        "option_e": "Tiradentes",
        "correct_answer": AnswerChoice.B,
        "subject": "História",
        "source": "ENEM",
        "year": 2016
    },
    {
        "statement": "Qual a probabilidade de lançar um dado comum e sair um número par?",
        "option_a": "1/6",
        "option_b": "1/3",
        "option_c": "1/2",
        "option_d": "2/3",
        "option_e": "5/6",
        "correct_answer": AnswerChoice.C,
        "subject": "Matemática",
        "source": "OBMEP",
        "year": 2021
    },
    {
        "statement": "O bioma Pantanal é considerado a maior planície de inundação do mundo e localiza-se nos estados de:",
        "option_a": "Goiás e Tocantins",
        "option_b": "Mato Grosso e Mato Grosso do Sul",
        "option_c": "Paraná e Santa Catarina",
        "option_d": "Amazonas e Roraima",
        "option_e": "Minas Gerais e Bahia",
        "correct_answer": AnswerChoice.B,
        "subject": "Geografia",
        "source": "ENEM",
        "year": 2020
    },
    {
        "statement": "Qual cientista propôs o modelo atômico conhecido como 'pudim de passas'?",
        "option_a": "Dalton",
        "option_b": "Thomson",
        "option_c": "Rutherford",
        "option_d": "Bohr",
        "option_e": "Mendeleev",
        "correct_answer": AnswerChoice.B,
        "subject": "Química",
        "source": "UNICAMP",
        "year": 2018
    },
    {
        "statement": "O som é uma onda do tipo:",
        "option_a": "Eletromagnética e transversal",
        "option_b": "Mecânica e longitudinal",
        "option_c": "Mecânica e transversal",
        "option_d": "Eletromagnética e longitudinal",
        "option_e": "Estacionária apenas",
        "correct_answer": AnswerChoice.B,
        "subject": "Física",
        "source": "FATEC",
        "year": 2022
    },
    {
        "statement": "A produção de sementes e frutos é uma característica exclusiva das:",
        "option_a": "Briófitas",
        "option_b": "Pteridófitas",
        "option_c": "Gimnospermas",
        "option_d": "Angiospermas",
        "option_e": "Algas verdes",
        "correct_answer": AnswerChoice.D,
        "subject": "Biologia",
        "source": "ENEM",
        "year": 2023
    },
    {
        "statement": "Qual é a medida de um ângulo reto?",
        "option_a": "45°",
        "option_b": "90°",
        "option_c": "180°",
        "option_d": "270°",
        "option_e": "360°",
        "correct_answer": AnswerChoice.B,
        "subject": "Matemática",
        "source": "Vunesp",
        "year": 2021
    },
    {
        "statement": "O Iluminismo influenciou diretamente qual desses movimentos na América?",
        "option_a": "Revolta de Beckman",
        "option_b": "Guerra dos Mascates",
        "option_c": "Independência dos Estados Unidos",
        "option_d": "Expulsão dos Holandeses",
        "option_e": "Tratado de Madri",
        "correct_answer": AnswerChoice.C,
        "subject": "História",
        "source": "FUVEST",
        "year": 2022
    },
    {
        "statement": "A camada de ozônio protege a Terra de qual tipo de radiação?",
        "option_a": "Infravermelha",
        "option_b": "Micro-ondas",
        "option_c": "Ultravioleta",
        "option_d": "Raios X",
        "option_e": "Ondas de rádio",
        "correct_answer": AnswerChoice.C,
        "subject": "Geografia",
        "source": "ENEM",
        "year": 2017
    },
    {
        "statement": "O ferro enferruja devido a uma reação de:",
        "option_a": "Substituição",
        "option_b": "Adição",
        "option_c": "Oxirredução",
        "option_d": "Neutralização",
        "option_e": "Saponificação",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "FUVEST",
        "year": 2020
    },
    {
        "statement": "Qual a principal função das plaquetas no sangue?",
        "option_a": "Transporte de oxigênio",
        "option_b": "Defesa contra vírus",
        "option_c": "Coagulação sanguínea",
        "option_d": "Produção de anticorpos",
        "option_e": "Transporte de nutrientes",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "UNESP",
        "year": 2021
    },
    {
        "statement": "A função horária do espaço S = 10 + 2t descreve um movimento:",
        "option_a": "Uniforme com velocidade 10 m/s",
        "option_b": "Uniformemente variado com aceleração 2 m/s²",
        "option_c": "Uniforme com velocidade 2 m/s",
        "option_d": "Retrógrado",
        "option_e": "Circular uniforme",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "ENEM",
        "year": 2014
    },
    {
        "statement": "A capital da Alemanha é:",
        "option_a": "Munique",
        "option_b": "Hamburgo",
        "option_c": "Berlim",
        "option_d": "Frankfurt",
        "option_e": "Colônia",
        "correct_answer": AnswerChoice.C,
        "subject": "Geografia",
        "source": "Vunesp",
        "year": 2020
    },
    {
        "statement": "O volume de um cubo de aresta 3 cm é:",
        "option_a": "9 cm³",
        "option_b": "18 cm³",
        "option_c": "27 cm³",
        "option_d": "36 cm³",
        "option_e": "81 cm³",
        "correct_answer": AnswerChoice.C,
        "subject": "Matemática",
        "source": "OBMEP",
        "year": 2019
    },
    {
        "statement": "A 'Pax Romana' foi um período de relativa paz e estabilidade no:",
        "option_a": "Império Grego",
        "option_b": "Império Romano",
        "option_c": "Império Bizantino",
        "option_d": "Egito Antigo",
        "option_e": "Império Carolíngio",
        "correct_answer": AnswerChoice.B,
        "subject": "História",
        "source": "FUVEST",
        "year": 2021
    },
    {
        "statement": "Qual destes é um exemplo de recurso renovável?",
        "option_a": "Petróleo",
        "option_b": "Gás Natural",
        "option_c": "Energia Eólica",
        "option_d": "Carvão Mineral",
        "option_e": "Urânio",
        "correct_answer": AnswerChoice.C,
        "subject": "Geografia",
        "source": "ENEM",
        "year": 2022
    },
    {
        "statement": "A ligação química entre dois ametais é geralmente:",
        "option_a": "Iônica",
        "option_b": "Metálica",
        "option_c": "Covalente",
        "option_d": "De hidrogênio",
        "option_e": "Dipolo-induzido",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "UNESP",
        "year": 2021
    },
    {
        "statement": "O hormônio responsável pelo crescimento das plantas e pelo tropismo é a:",
        "option_a": "Insulina",
        "option_b": "Auxina",
        "option_c": "Adrenalina",
        "option_d": "Tiroxina",
        "option_e": "Prolactina",
        "correct_answer": AnswerChoice.B,
        "subject": "Biologia",
        "source": "ENEM",
        "year": 2020
    },
    {
        "statement": "Qual o logaritmo de 1 na base 10?",
        "option_a": "0",
        "option_b": "1",
        "option_c": "10",
        "option_d": "Indeterminado",
        "option_e": "-1",
        "correct_answer": AnswerChoice.A,
        "subject": "Matemática",
        "source": "Vunesp",
        "year": 2022
    },
    {
        "statement": "A pressão exercida por um fluido em repouso aumenta com a:",
        "option_a": "Área da superfície",
        "option_b": "Velocidade do fluido",
        "option_c": "Profundidade",
        "option_d": "Temperatura apenas",
        "option_e": "Cor do fluido",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "ENEM",
        "year": 2019
    },
    {
        "statement": "Qual o principal gás da atmosfera terrestre?",
        "option_a": "Oxigênio",
        "option_b": "Nitrogênio",
        "option_c": "Argônio",
        "option_d": "Gás Carbônico",
        "option_e": "Hidrogênio",
        "correct_answer": AnswerChoice.B,
        "subject": "Geografia",
        "source": "FUVEST",
        "year": 2020
    },
    {
        "statement": "A 'Guerra dos Farrapos' ocorreu na província de:",
        "option_a": "Bahia",
        "option_b": "Pernambuco",
        "option_c": "Rio Grande do Sul",
        "option_d": "Minas Gerais",
        "option_e": "Maranhão",
        "correct_answer": AnswerChoice.C,
        "subject": "História",
        "source": "ENEM",
        "year": 2017
    },
    {
        "statement": "O grupo funcional -OH ligado a um carbono saturado caracteriza um:",
        "option_a": "Aldeído",
        "option_b": "Ácido Carboxílico",
        "option_c": "Álcool",
        "option_d": "Cetona",
        "option_e": "Éter",
        "correct_answer": AnswerChoice.C,
        "subject": "Química",
        "source": "UNICAMP",
        "year": 2022
    },
    {
        "statement": "Quantos cromossomos possui uma célula somática humana normal?",
        "option_a": "23",
        "option_b": "44",
        "option_c": "46",
        "option_d": "48",
        "option_e": "52",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "ENEM",
        "year": 2019
    },
    {
        "statement": "O teorema de Pitágoras afirma que em um triângulo retângulo:",
        "option_a": "a + b = c",
        "option_b": "a² + b² = c²",
        "option_c": "a² - b² = c²",
        "option_d": "ab = c",
        "option_e": "2a + 2b = c",
        "correct_answer": AnswerChoice.B,
        "subject": "Matemática",
        "source": "FATEC",
        "year": 2021
    },
    {
        "statement": "A Primeira Grande Guerra (1914-1918) teve como estopim o assassinato de:",
        "option_a": "Adolf Hitler",
        "option_b": "Franz Ferdinand (Francisco Ferdinando)",
        "option_c": "Winston Churchill",
        "option_d": "Czar Nicolau II",
        "option_e": "Napoleão III",
        "correct_answer": AnswerChoice.B,
        "subject": "História",
        "source": "FUVEST",
        "year": 2020
    },
    {
        "statement": "Qual o maior país do mundo em extensão territorial?",
        "option_a": "Canadá",
        "option_b": "China",
        "option_c": "Rússia",
        "option_d": "EUA",
        "option_e": "Brasil",
        "correct_answer": AnswerChoice.C,
        "subject": "Geografia",
        "source": "OBMEP",
        "year": 2018
    },
    {
        "statement": "O índice de refração de um meio é a razão entre a velocidade da luz no vácuo e a:",
        "option_a": "Velocidade do som",
        "option_b": "Velocidade da luz no meio",
        "option_c": "Densidade do meio",
        "option_d": "Frequência da luz",
        "option_e": "Comprimento de onda",
        "correct_answer": AnswerChoice.B,
        "subject": "Física",
        "source": "ENEM",
        "year": 2021
    },
    {
        "statement": "A polinização realizada pelo vento é chamada de:",
        "option_a": "Entomofilia",
        "option_b": "Ornitofilia",
        "option_c": "Anemofilia",
        "option_d": "Quiropterofilia",
        "option_e": "Hidrofilia",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "UNESP",
        "year": 2022
    },
    {
        "statement": "O zero absoluto na escala Kelvin corresponde a qual temperatura em Celsius?",
        "option_a": "0°C",
        "option_b": "100°C",
        "option_c": "-273,15°C",
        "option_d": "-100°C",
        "option_e": "273,15°C",
        "correct_answer": AnswerChoice.C,
        "subject": "Física",
        "source": "ITA",
        "year": 2019
    },
    {
        "statement": "A principal reserva de energia a longo prazo nos animais é o(a):",
        "option_a": "Glicogênio",
        "option_b": "Amido",
        "option_c": "Gordura (Lipídio)",
        "option_d": "Proteína",
        "option_e": "Celulose",
        "correct_answer": AnswerChoice.C,
        "subject": "Biologia",
        "source": "UNICAMP",
        "year": 2023
    },
    {
        "statement": "Qual a raiz da função f(x) = 5x - 20?",
        "option_a": "2",
        "option_b": "4",
        "option_c": "5",
        "option_d": "10",
        "option_e": "20",
        "correct_answer": AnswerChoice.B,
        "subject": "Matemática",
        "source": "Vunesp",
        "year": 2022
    },
    {
        "statement": "O 'Ciclo do Café' no Brasil teve seu auge em qual estado?",
        "option_a": "Bahia",
        "option_b": "São Paulo",
        "option_c": "Ceará",
        "option_d": "Amazonas",
        "option_e": "Santa Catarina",
        "correct_answer": AnswerChoice.B,
        "subject": "História",
        "source": "ENEM",
        "year": 2015
    },
    {
        "statement": "O elemento químico Ouro tem como símbolo:",
        "option_a": "Ag",
        "option_b": "Au",
        "option_c": "Fe",
        "option_d": "Cu",
        "option_e": "Pb",
        "correct_answer": AnswerChoice.B,
        "subject": "Química",
        "source": "ENEM",
        "year": 2018
    },
    {
        "statement": "Qual bioma brasileiro é conhecido como 'Savana Brasileira'?",
        "option_a": "Caatinga",
        "option_b": "Cerrado",
        "option_c": "Pampa",
        "option_d": "Mata de Cocais",
        "option_e": "Pantanal",
        "correct_answer": AnswerChoice.B,
        "subject": "Geografia",
        "source": "UNICAMP",
        "year": 2021
    },
    {
        "statement": "A aceleração centrípeta é responsável por:",
        "option_a": "Alterar o módulo da velocidade",
        "option_b": "Alterar a direção da velocidade",
        "option_c": "Aumentar a energia cinética",
        "option_d": "Reduzir o atrito",
        "option_e": "Parar o movimento",
        "correct_answer": AnswerChoice.B,
        "subject": "Física",
        "source": "FUVEST",
        "year": 2023
    }
]



def seed_user():
    if User.query.filter_by(email="test@example.com").first():
        print("Usuário de testes já existe, pulando.")
        return
    user = User(
        name="Usuário de Testes",  # type: ignore
        email="test@example.com",  # type: ignore
        password=generate_password_hash("password123"),  # type: ignore
    )
    db.session.add(user)
    db.session.commit()
    print(f"Usuário criado: {user.email}")


def seed_questions():
    if Question.query.first():
        print("Questões já existem, pulando.")
        return
    for data in QUESTIONS:
        db.session.add(Question(**data))  # type: ignore
    db.session.commit()
    print(f"{len(QUESTIONS)} questões criadas.")


def seed():
    app = create_app()
    with app.app_context():
        seed_user()
        seed_questions()


if __name__ == "__main__":
    seed()
