"""add google_id to users and make password nullable

Revision ID: aaf8790e6592
Revises: 713fe43e4fea
Create Date: 2026-05-11 19:36:44.706899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf8790e6592'
down_revision = '713fe43e4fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=128), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
